inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - metadata.rb
    - Gemfile
    - attributes/**
    - libraries/**
    - providers/**
    - recipes/**
    - resources/**
    - spec/**
  Exclude:
    - .cookbooks/**/*
    - berks-cookbooks/**/*
    - .bundle/**/*
